/*
 * File: generate-ui.mjs
 * Purpose: Validate canonical YAML and mechanically emit native-safe constants/assets.
 * Author: Codex; Contact: michael@mandedesign.studio
 * License: SPDX-License-Identifier: MPL-2.0
 * Decision: DEV-2026-09-07-025
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { parseDocument } from 'yaml';

const root = fileURLToPath(new URL('../', import.meta.url));
const base = path.join(root, 'src/ui');
/* Purpose: Read one declared spec. Design: Fail on duplicate keys/parse errors.
 * Workflow: Build-time only. Data Handoff: Plain YAML data, never executable code. */
function read(relative) {
  const filename = path.resolve(base, relative);
  assert(filename.startsWith(base + path.sep), 'Manifest path escapes src/ui');
  const document = parseDocument(fs.readFileSync(filename, 'utf8'));
  assert.equal(document.errors.length, 0, `${relative}: ${document.errors}`);
  return document.toJS();
}
const manifest = read('ui.yaml').ui;
assert.equal(manifest.version, 1);
const spec = {
  theme: read(manifest.theme).theme,
  typography: read(manifest.typography).typography,
  layout: read(manifest.layout).layout,
  components: Object.fromEntries(Object.entries(manifest.components).map(([id, p]) => {
    const component = read(p).component;
    assert.equal(component.id, id, `Component id mismatch: ${p}`);
    return [id, component];
  })),
};
const names = fs.readdirSync(path.join(root, 'assets/hud')).filter(p => p.endsWith('.svg')).sort();
const assets = new Set(names.map(p => p.slice(0, -4)));
/* Purpose: Reject dangling visual references. Design: Traverse declarative roles.
 * Workflow: Every generation/check. Data Handoff: Throws before stale code is used. */
function validate(value, key = '') {
  if (typeof value === 'string') {
    assert(!value.includes('TODO') && !value.includes('{theme'), `Unresolved ${value}`);
    if (['asset', 'bezel', 'shape', 'newShape', 'activeShape', 'newActiveShape', 'addPlate', 'paintedWashAsset'].includes(key)) {
      assert(assets.has(value), `Missing SVG: ${value}`);
    }
    if (['color', 'activeColor', 'newColor', 'addColor', 'surface'].includes(key)) {
      assert(value in spec.theme.colors, `Unknown color: ${value}`);
    }
    if (key === 'typography') assert(value in spec.typography.styles);
  } else if (Array.isArray(value)) {
    value.forEach(v => validate(v, key === 'assets' || key === 'referenceOnly' ? 'asset' : key));
  } else if (value && typeof value === 'object') {
    Object.entries(value).forEach(([k, v]) => validate(v, k));
  }
}
validate(spec.components);
validate(spec.layout);
validate(spec.theme.effects);
Object.values(spec.theme.colors).forEach(color => assert(/^#[\da-f]{6}$/i.test(color)));
for (const item of spec.components.action_dock.items) assert(assets.has(item.icon));
assert(assets.has(spec.components.navigation_rail.menu.icon));
assert(assets.has(spec.components.viewport.border));
for (const [id, r] of Object.entries(spec.layout.regions)) {
  assert(r.width > 0 && r.height > 0 && r.x >= 0 && r.y >= 0, id);
  assert(r.x + r.width <= 390 && r.y + r.height <= 844, `${id} outside design bounds`);
}
assert.deepEqual(spec.components.navigation_rail.contexts.home, ['new', 'log', 'search', 'graph']);
assert.deepEqual(spec.components.navigation_rail.contexts.capture, ['commit', 'cancel']);
assert.equal(spec.components.scanner.inner.direction, 'clockwise');
assert.equal(spec.components.scanner.outer.direction, 'counterclockwise');
const header = '/* GENERATED by scripts/generate-ui.mjs from YAML/Figma SVGs. Do not edit.\n * Author: Codex; Contact: michael@mandedesign.studio; SPDX-License-Identifier: MPL-2.0\n * DEV-2026-09-07-025 */\n';
const outputs = {
  'uiSpec.ts': header + `export const uiSpec = ${JSON.stringify(spec, null, 2)} as const;\n`,
  'hudAssets.ts': header + 'export const hudAssets = {\n' + names.map(p => `  '${p.slice(0, -4)}': require('../../../assets/hud/${p}'),`).join('\n') + '\n} as const;\nexport type HudAsset = keyof typeof hudAssets;\n',
};
for (const [name, contents] of Object.entries(outputs)) {
  const target = path.join(base, 'generated', name);
  if (process.argv.includes('--check')) {
    assert.equal(fs.readFileSync(target, 'utf8'), contents, `Stale generated file: ${name}`);
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, contents);
  }
}
console.log(`UI specification PASS: 10 YAML files, ${assets.size} SVG assets; ${process.argv.includes('--check') ? 'generation current' : 'generated'}`);
